USE [master]
GO

/****** Object:  Database [PatientTest]    Script Date: 27/08/2020 14:46:36 ******/
CREATE DATABASE [PatientTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PatientTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatientTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PatientTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatientTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatientTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PatientTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PatientTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PatientTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PatientTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [PatientTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PatientTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatientTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatientTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatientTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PatientTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PatientTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatientTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PatientTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatientTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PatientTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatientTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatientTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatientTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatientTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatientTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PatientTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatientTest] SET RECOVERY FULL 
GO

ALTER DATABASE [PatientTest] SET  MULTI_USER 
GO

ALTER DATABASE [PatientTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatientTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatientTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatientTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PatientTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatientTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PatientTest] SET  READ_WRITE 
GO

